// <auto-generated />
using System;
using EndomondoJsonToSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EndomondoJsonToSQL.Migrations
{
    [DbContext(typeof(EndomondoContext))]
    [Migration("20201122021234_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EndomondoJsonToSQL.EndomondoWorkout", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double?>("AltitudeMaxM")
                        .HasColumnType("float");

                    b.Property<double?>("AltitudeMinM")
                        .HasColumnType("float");

                    b.Property<double?>("AscendM")
                        .HasColumnType("float");

                    b.Property<double?>("CaloriesKcal")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("DescendM")
                        .HasColumnType("float");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<double?>("DurationS")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SpeedAvgKmh")
                        .HasColumnType("float");

                    b.Property<double?>("SpeedMaxKmh")
                        .HasColumnType("float");

                    b.Property<string>("Sport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
